server:
    port: 8080
spring:
    application:
        name: customer
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/demokhanhtt?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: sammy
        password: password
        hikari:
            poolName: Hikari
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
        addresses: localhost:5672
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

